"""Phase 2b approval gate — file-system semaphore + DB row helpers.

The bridge spawns `claude -p` with a PreToolUse hook (registered under
`CHAT_CWD/.claude/settings.json`). When Claude wants to use a write
tool, the hook writes a JSON request to `${STATE_DIR}/approvals/requests/`
and polls `${STATE_DIR}/approvals/decisions/<tool_use_id>` until either
the bridge writes a decision or the hook's own deadline passes.

This module owns:

- The directory layout (`requests/`, `decisions/`, `archive/`).
- The hook script + per-CWD `.claude/settings.json` bootstrap (the
  bridge calls `bootstrap_hooks()` on startup so it works on a fresh
  host with no manual setup).
- DB CRUD on `pending_approvals` (the table is created in `app.py`'s
  `DB_SCHEMA`; the migration helper there adds Phase 2b columns to
  pre-existing DBs).
- The decision-file writer that emits the exact `hookSpecificOutput`
  JSON Claude Code expects.

Design notes:

- We deliberately use file-system polling instead of HTTP loopback or
  Unix sockets. The hook is a bash script that already knows how to
  read files; adding curl + a port adds attack surface and a moving
  part. The cost is poll latency (~1s) which is invisible compared to
  the human approval round-trip.
- Decision files are atomically written via tempfile + rename, so the
  hook can't read a partially-written JSON.
- Concurrent tool calls get unique `tool_use_id`s from Claude Code, so
  the dirs don't collide.
"""

from __future__ import annotations

import asyncio
import json
import os
import shutil
import sqlite3
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import structlog

log = structlog.get_logger("approvals")


# ── Paths ────────────────────────────────────────────────────────────────


def approvals_dir(state_dir: Path) -> Path:
    return state_dir / "approvals"


def requests_dir(state_dir: Path) -> Path:
    return approvals_dir(state_dir) / "requests"


def decisions_dir(state_dir: Path) -> Path:
    return approvals_dir(state_dir) / "decisions"


def archive_dir(state_dir: Path) -> Path:
    return approvals_dir(state_dir) / "archive"


def ensure_dirs(state_dir: Path) -> None:
    """Create the 3 dirs if missing. Safe to call repeatedly."""
    for d in (requests_dir(state_dir), decisions_dir(state_dir), archive_dir(state_dir)):
        d.mkdir(parents=True, exist_ok=True)


# ── Hook script + settings.json bootstrap ────────────────────────────────


HOOK_SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
# Auto-generated by agent-me bridge — do NOT edit by hand.
# Source: src/agent_me/slack_bridge/approvals.py::HOOK_SCRIPT_TEMPLATE
#
# This script runs once per write-tool invocation under `claude -p`.
# It writes the request JSON to APPROVALS_DIR/requests/<tool_use_id>.json,
# polls APPROVALS_DIR/decisions/<tool_use_id> until the bridge writes a
# decision, then prints that decision (which Claude Code parses as the
# hook's `hookSpecificOutput` JSON) and exits 0.
#
# Timeout default 300s — denies safely if no human responds.
set -euo pipefail

APPROVALS_DIR="${{AGENT_ME_APPROVALS_DIR:-{approvals_dir}}}"
mkdir -p "$APPROVALS_DIR/requests" "$APPROVALS_DIR/decisions"

INPUT="$(cat)"
TOOL_ID="$(printf '%s' "$INPUT" | jq -r '.tool_use_id // .tool_use_id // empty')"

if [[ -z "$TOOL_ID" ]]; then
    # No tool_use_id — Claude Code shape changed; fail closed.
    printf '%s' '{{"hookSpecificOutput":{{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"hook: missing tool_use_id"}}}}'
    exit 0
fi

REQ="$APPROVALS_DIR/requests/${{TOOL_ID}}.json"
DEC="$APPROVALS_DIR/decisions/${{TOOL_ID}}"

# Atomic write so the bridge never reads a partial request.
TMP="$(mktemp "$APPROVALS_DIR/requests/.${{TOOL_ID}}.XXXXXX")"
printf '%s' "$INPUT" > "$TMP"
mv "$TMP" "$REQ"

DEADLINE=$(( $(date +%s) + ${{AGENT_ME_APPROVAL_SECS:-300}} ))
while (( $(date +%s) < DEADLINE )); do
    if [[ -f "$DEC" ]]; then
        cat "$DEC"
        rm -f "$DEC" "$REQ"
        exit 0
    fi
    sleep 1
done

# Timeout — fail closed. Bridge can still see the request file in archive.
mv "$REQ" "$APPROVALS_DIR/archive/${{TOOL_ID}}.timeout.json" 2>/dev/null || true
printf '%s' '{{"hookSpecificOutput":{{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"hook: human approval timeout (300s)"}}}}'
exit 0
"""


# Matcher: anything that mutates state. Keep `Read|Grep|Glob|WebFetch|
# WebSearch` OUT of this list — they should run unobstructed.
HOOK_MATCHER = (
    "Write|Edit|NotebookEdit|Bash|"
    "mcp__maas-jira__jira_create_issue|"
    "mcp__maas-jira__jira_clone_issue|"
    "mcp__maas-jira__jira_update_issue|"
    "mcp__maas-jira__jira_transition_issue|"
    "mcp__maas-nvbugs__nvbugs_update_bug.*|"
    "mcp__maas-ippsec__register_repo|"
    "mcp__maas-mysql__execute_sql|"
    "mcp__maas-gitlab__gitlab_coderabbit_ai_prompt|"
    "mcp__maas-gitlab__gitlab_greptile_ai_suggestions"
)


def hook_settings_blob(hook_path: Path) -> dict[str, Any]:
    """The `.claude/settings.json` blob Claude Code reads.

    `defaultMode: bypassPermissions` is preserved so unmatched tools
    (Read/Grep/etc.) run without prompting; the matcher narrows the
    hook to write tools only.
    """
    return {
        "permissions": {
            "defaultMode": "bypassPermissions",
        },
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": HOOK_MATCHER,
                    "hooks": [
                        {
                            "type": "command",
                            "command": str(hook_path),
                            "timeout": 600,  # seconds; bridge enforces its own approval window
                        }
                    ],
                }
            ]
        },
    }


def bootstrap_hooks(chat_cwd: Path, state_dir: Path) -> Path:
    """Write `.claude/settings.json` and `.claude/hooks/slack-approval.sh`
    into `chat_cwd` so claude -p invocations there pick them up.

    Returns the hook script path. Idempotent — overwrites both files
    on every bridge startup so a fresh state_dir on a new host works
    without manual setup.
    """
    ensure_dirs(state_dir)
    hooks_dir = chat_cwd / ".claude" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "slack-approval.sh"
    hook_path.write_text(
        HOOK_SCRIPT_TEMPLATE.format(approvals_dir=approvals_dir(state_dir))
    )
    hook_path.chmod(0o755)

    settings_path = chat_cwd / ".claude" / "settings.json"
    settings_path.write_text(
        json.dumps(hook_settings_blob(hook_path), indent=2) + "\n"
    )
    log.info("hooks_bootstrapped",
             chat_cwd=str(chat_cwd),
             hook=str(hook_path),
             settings=str(settings_path))
    return hook_path


# ── Decision-file writer ─────────────────────────────────────────────────


def _hook_output(decision: str, reason: str) -> dict[str, Any]:
    """The exact JSON shape Claude Code's PreToolUse hook expects."""
    return {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": decision,  # allow | deny | ask | defer
            "permissionDecisionReason": reason,
        }
    }


def write_decision(state_dir: Path, tool_use_id: str,
                   decision: str, reason: str) -> Path:
    """Atomically write a decision file the hook is polling for.

    Returns the destination path. Tempfile + os.replace keeps the hook
    from ever reading a partially-written line.
    """
    if decision not in ("allow", "deny", "ask", "defer"):
        raise ValueError(f"invalid decision: {decision!r}")
    target = decisions_dir(state_dir) / tool_use_id
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(f".{uuid.uuid4().hex[:8]}.tmp")
    tmp.write_text(json.dumps(_hook_output(decision, reason)))
    os.replace(tmp, target)
    log.info("decision_written", tool_use_id=tool_use_id, decision=decision)
    return target


# ── Request scanning ─────────────────────────────────────────────────────


@dataclass
class ApprovalRequest:
    tool_use_id: str
    tool_name: str
    tool_input: dict[str, Any]
    session_id: str | None
    cwd: str | None
    transcript_path: str | None
    raw: dict[str, Any]
    request_path: Path


def parse_request(path: Path) -> ApprovalRequest | None:
    """Read a hook request file and return a typed view of it.

    Returns None if the file is malformed; the caller should move bad
    files to `archive/` so we don't re-read them every poll.
    """
    try:
        raw = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        log.warning("approval_request_read_failed", path=str(path), err=str(exc))
        return None
    return ApprovalRequest(
        tool_use_id=str(raw.get("tool_use_id") or path.stem),
        tool_name=str(raw.get("tool_name") or "?"),
        tool_input=raw.get("tool_input") or {},
        session_id=raw.get("session_id"),
        cwd=raw.get("cwd"),
        transcript_path=raw.get("transcript_path"),
        raw=raw,
        request_path=path,
    )


def scan_pending_requests(state_dir: Path) -> list[ApprovalRequest]:
    """Return all currently pending request files (not in archive)."""
    out: list[ApprovalRequest] = []
    for p in sorted(requests_dir(state_dir).glob("*.json")):
        if p.name.startswith("."):
            continue  # skip in-flight tempfiles from atomic writes
        req = parse_request(p)
        if req is not None:
            out.append(req)
    return out


def archive_request(state_dir: Path, tool_use_id: str, status: str) -> None:
    """Move a request file into archive/ once the decision is written.

    Status is appended to the filename for forensics (`approved`,
    `rejected`, `expired`).
    """
    src = requests_dir(state_dir) / f"{tool_use_id}.json"
    if not src.exists():
        return
    dst = archive_dir(state_dir) / f"{tool_use_id}.{status}.{int(time.time())}.json"
    dst.parent.mkdir(parents=True, exist_ok=True)
    src.rename(dst)


# ── DB CRUD ──────────────────────────────────────────────────────────────


def insert_pending(
    db: sqlite3.Connection,
    *,
    approval_id: str,
    thread_ts: str,
    tool_use_id: str,
    tool_name: str,
    tool_input_json: str,
    session_id: str | None,
    slack_channel: str | None,
    slack_message_ts: str | None,
) -> None:
    """Insert one pending row. action_type mirrors tool_name for back-
    compat with code that filtered on action_type."""
    now = int(time.time() * 1000)
    db.execute(
        """INSERT INTO pending_approvals (
              id, thread_ts, action_type, payload_json, status,
              slack_message_ts, created_at, resolved_at,
              tool_use_id, session_id, tool_name, slack_channel
           ) VALUES (?, ?, ?, ?, 'pending', ?, ?, NULL, ?, ?, ?, ?)""",
        (approval_id, thread_ts, tool_name, tool_input_json,
         slack_message_ts, now, tool_use_id, session_id, tool_name,
         slack_channel),
    )


def resolve(
    db: sqlite3.Connection,
    *,
    approval_id: str,
    status: str,
    decision_reason: str | None = None,
    auto: bool = False,
) -> dict[str, Any] | None:
    """Mark a pending row resolved. Returns the row dict (or None if missing).

    `status` ∈ {'approved', 'rejected', 'expired'}.
    """
    if status not in ("approved", "rejected", "expired"):
        raise ValueError(f"invalid status: {status!r}")
    now = int(time.time() * 1000)
    db.execute(
        """UPDATE pending_approvals
              SET status = ?,
                  resolved_at = ?,
                  decision_reason = ?,
                  auto_approved = ?
            WHERE id = ?""",
        (status, now, decision_reason, 1 if auto else 0, approval_id),
    )
    return get_by_id(db, approval_id)


def get_by_id(db: sqlite3.Connection, approval_id: str) -> dict[str, Any] | None:
    row = db.execute(
        """SELECT id, thread_ts, tool_use_id, session_id, tool_name,
                  payload_json, status, slack_message_ts, slack_channel,
                  decision_reason, auto_approved, created_at, resolved_at
             FROM pending_approvals
            WHERE id = ?""",
        (approval_id,),
    ).fetchone()
    return _row_to_dict(row)


def get_by_tool_use_id(db: sqlite3.Connection, tool_use_id: str) -> dict[str, Any] | None:
    row = db.execute(
        """SELECT id, thread_ts, tool_use_id, session_id, tool_name,
                  payload_json, status, slack_message_ts, slack_channel,
                  decision_reason, auto_approved, created_at, resolved_at
             FROM pending_approvals
            WHERE tool_use_id = ?
            ORDER BY created_at DESC
            LIMIT 1""",
        (tool_use_id,),
    ).fetchone()
    return _row_to_dict(row)


def _row_to_dict(row: Any) -> dict[str, Any] | None:
    if row is None:
        return None
    cols = ("id", "thread_ts", "tool_use_id", "session_id", "tool_name",
            "payload_json", "status", "slack_message_ts", "slack_channel",
            "decision_reason", "auto_approved", "created_at", "resolved_at")
    return dict(zip(cols, row, strict=False))


# ── Auto-approve toggle (per-thread) ─────────────────────────────────────


def thread_auto_approve(db: sqlite3.Connection, thread_ts: str) -> bool:
    row = db.execute(
        "SELECT auto_approve FROM threads WHERE thread_ts = ?",
        (thread_ts,),
    ).fetchone()
    return bool(row and row[0])


def set_thread_auto_approve(db: sqlite3.Connection, thread_ts: str, on: bool) -> None:
    db.execute(
        "UPDATE threads SET auto_approve = ? WHERE thread_ts = ?",
        (1 if on else 0, thread_ts),
    )


# ── Helpers for the watcher loop ─────────────────────────────────────────


def expire_stale_pending(db: sqlite3.Connection, max_age_s: int = 600) -> int:
    """Mark old pending rows expired. Called periodically by the loop.

    Returns the number of rows expired. The hook script also has its
    own 300s timeout; this is the bridge-side safety net.
    """
    cutoff = int(time.time() * 1000) - max_age_s * 1000
    cur = db.execute(
        """UPDATE pending_approvals
              SET status = 'expired',
                  resolved_at = ?,
                  decision_reason = 'bridge: pending too long'
            WHERE status = 'pending'
              AND created_at < ?""",
        (int(time.time() * 1000), cutoff),
    )
    return cur.rowcount or 0


async def approval_loop(
    *,
    db: sqlite3.Connection,
    state_dir: Path,
    on_request,
    poll_interval_s: float = 1.0,
) -> None:
    """Forever-loop: scan requests/, hand new ones to `on_request`.

    `on_request(req: ApprovalRequest) -> None` is awaited per new
    request. The caller is responsible for inserting a DB row + posting
    to Slack + writing a decision file when the user clicks. We just
    feed it new requests, idempotently.

    Idempotency: we track which tool_use_ids we've already handed off
    in-process. The caller should also check the DB before re-posting
    if needed.
    """
    seen: set[str] = set()
    while True:
        try:
            for req in scan_pending_requests(state_dir):
                if req.tool_use_id in seen:
                    continue
                # Skip if already in DB as anything but pending — means we
                # restarted while a request was in flight; the previous
                # bridge instance handled it (or it was already resolved).
                existing = get_by_tool_use_id(db, req.tool_use_id)
                if existing and existing["status"] != "pending":
                    seen.add(req.tool_use_id)
                    continue
                seen.add(req.tool_use_id)
                try:
                    await on_request(req)
                except Exception as exc:
                    log.error("approval_on_request_failed",
                              tool_use_id=req.tool_use_id, err=str(exc))
            # Periodic cleanup
            if int(time.time()) % 60 == 0:
                expired = expire_stale_pending(db)
                if expired:
                    log.info("approvals_expired", count=expired)
        except Exception as exc:
            log.error("approval_loop_iter_failed", err=str(exc))
        await asyncio.sleep(poll_interval_s)


# ── Convenience: format request for Slack ────────────────────────────────


def format_request_for_slack(req: ApprovalRequest) -> tuple[str, list[dict[str, Any]]]:
    """Render an approval request as Slack blocks.

    Two sections + two buttons (Approve/Reject). The action_id encodes
    the approval row's `id` (UUID short form) so the handler can look
    up the row in O(1) without parsing free-form text. We keep the
    raw `tool_use_id` in the button `value` (Slack permits up to 2K).
    """
    tool = req.tool_name or "?"
    tool_input_pretty = json.dumps(req.tool_input, indent=2, ensure_ascii=False)
    if len(tool_input_pretty) > 2500:
        tool_input_pretty = tool_input_pretty[:2500] + "\n…[truncated]"
    return (tool, _slack_blocks(req, tool, tool_input_pretty))


def _slack_blocks(req: ApprovalRequest, tool: str, pretty_input: str) -> list[dict[str, Any]]:
    short_id = req.tool_use_id[:12]
    return [
        {"type": "header",
         "text": {"type": "plain_text",
                  "text": f"⚠️ Tool wants approval: {tool}"}},
        {"type": "context",
         "elements": [{"type": "mrkdwn",
                       "text": f"_session `{(req.session_id or '?')[:8]}…` · tool_use_id `{short_id}`_"}]},
        {"type": "section",
         "text": {"type": "mrkdwn",
                  "text": f"```{pretty_input}```"}},
        {"type": "actions",
         "elements": [
             {"type": "button",
              "text": {"type": "plain_text", "text": "✅ Approve"},
              "style": "primary",
              "action_id": "approval_approve",
              "value": req.tool_use_id},
             {"type": "button",
              "text": {"type": "plain_text", "text": "❌ Reject"},
              "style": "danger",
              "action_id": "approval_reject",
              "value": req.tool_use_id},
             {"type": "button",
              "text": {"type": "plain_text", "text": "🔓 Auto-approve this thread"},
              "action_id": "approval_auto_thread",
              "value": req.tool_use_id},
         ]},
    ]


# ── External entry-point for tests / standalone tools ───────────────────


def reset_dirs(state_dir: Path) -> None:
    """Wipe and recreate the approvals dirs. Test / dev only."""
    if approvals_dir(state_dir).exists():
        shutil.rmtree(approvals_dir(state_dir))
    ensure_dirs(state_dir)
