#!/usr/bin/env bash
# Prepare Codex bearer-token MCP auth on the host.
#
# This runs on the remote host after ~/.claude/.credentials.json has been
# refreshed. It writes a chmod-600 shell env file containing the
# AGENT_ME_MCP_TOKEN_* exports expected by ~/.codex/config.toml and installs a
# small startup hook so future interactive shells inherit those vars before
# launching Codex.

set -euo pipefail

fail() { echo "✗ $*" >&2; exit 1; }
ok() { echo "✓ $*"; }

CREDENTIALS="${AGENT_ME_CLAUDE_MCP_CREDENTIALS:-$HOME/.claude/.credentials.json}"
ENV_FILE="${AGENT_ME_CODEX_MCP_ENV_FILE:-$HOME/.config/agent-me/codex-mcp-env.sh}"

if [[ ! -r "$CREDENTIALS" ]]; then
    fail "cannot read MCP credentials at $CREDENTIALS"
fi

if command -v python3 >/dev/null 2>&1; then
    PYTHON=python3
elif command -v python >/dev/null 2>&1; then
    PYTHON=python
else
    fail "python3/python not found on host"
fi

mkdir -p "$(dirname "$ENV_FILE")"
chmod 700 "$(dirname "$ENV_FILE")"

token_count="$("$PYTHON" - "$CREDENTIALS" "$ENV_FILE" <<'PY'
import json
import os
import re
import shlex
import stat
import sys
from pathlib import Path

cred_path = Path(sys.argv[1]).expanduser()
env_path = Path(sys.argv[2]).expanduser()

try:
    raw = json.loads(cred_path.read_text())
except FileNotFoundError:
    raise SystemExit(f"missing credentials file: {cred_path}")
except json.JSONDecodeError as exc:
    raise SystemExit(f"credentials file is not valid JSON: {exc}")

env = {}
for key, value in (raw.get("mcpOAuth") or {}).items():
    if not isinstance(value, dict):
        continue
    access = value.get("accessToken")
    if not access:
        continue
    server = value.get("serverName") or str(key).split("|", 1)[0]
    if not server.startswith("maas-"):
        continue
    suffix = re.sub(r"[^A-Za-z0-9]", "_", server).upper()
    env[f"AGENT_ME_MCP_TOKEN_{suffix}"] = str(access)

if not env:
    raise SystemExit("no maas-* MCP OAuth access tokens found in credentials")

lines = [
    "# Generated by agent-me/scripts/install-codex-mcp-env-on-host.sh.",
    "# Source this before starting Codex so MaaS bearer-token MCPs can authenticate.",
    "# Contains short-lived access tokens; keep this file private.",
]
for name in sorted(env):
    lines.append(f"export {name}={shlex.quote(env[name])}")

tmp_path = env_path.with_name(env_path.name + ".tmp")
tmp_path.write_text("\n".join(lines) + "\n")
os.chmod(tmp_path, stat.S_IRUSR | stat.S_IWUSR)
os.replace(tmp_path, env_path)
print(len(env))
PY
)"

chmod 600 "$ENV_FILE"
ok "wrote $token_count Codex MCP token export(s) to $ENV_FILE"

HOOK_BEGIN="# >>> agent-me Codex MCP env >>>"
HOOK_END="# <<< agent-me Codex MCP env <<<"

install_hook() {
    local rc_file="$1"
    local created=0

    if [[ ! -e "$rc_file" ]]; then
        : > "$rc_file"
        created=1
    fi

    if grep -qF "$HOOK_BEGIN" "$rc_file"; then
        return 1
    fi

    {
        if [[ -s "$rc_file" ]]; then
            printf '\n'
        fi
        printf '%s\n' "$HOOK_BEGIN"
        printf 'if [ -r "$HOME/.config/agent-me/codex-mcp-env.sh" ]; then\n'
        printf '    . "$HOME/.config/agent-me/codex-mcp-env.sh"\n'
        printf 'fi\n'
        printf '%s\n' "$HOOK_END"
    } >> "$rc_file"

    if [[ "$created" -eq 1 ]]; then
        chmod 600 "$rc_file"
    fi
    return 0
}

changed=()
unchanged=()

for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
    if install_hook "$rc"; then
        changed+=("$rc")
    else
        unchanged+=("$rc")
    fi
done

for rc in "$HOME/.profile" "$HOME/.bash_profile"; do
    if [[ -e "$rc" ]]; then
        if install_hook "$rc"; then
            changed+=("$rc")
        else
            unchanged+=("$rc")
        fi
    fi
done

if [[ "${#changed[@]}" -gt 0 ]]; then
    ok "installed Codex MCP env startup hook in: ${changed[*]}"
fi
if [[ "${#unchanged[@]}" -gt 0 ]]; then
    ok "Codex MCP env startup hook already present in: ${unchanged[*]}"
fi

ok "future shell-launched Codex sessions will inherit refreshed MCP auth"
