#!/usr/bin/env bash
# Run MaaS MCP reauth on this Mac, then sync refreshed credentials to a host.
#
# Usage:
#   ./scripts/mac-reauth-and-sync.sh <ssh-host> [-- <agent-me-codex-reauth args>]
#
# Why this exists:
# - OAuth callback URLs generated by the MCP auth helper point at
#   localhost:<port> on the machine running the helper.
# - If the bridge runs on Colossus but the browser is on a Mac, opening those
#   Colossus-generated URLs directly on the Mac sends the callback to the Mac,
#   not Colossus, unless every callback port is SSH-forwarded.
# - The reliable path is therefore: run the auth helper on the Mac, let macOS
#   open the browser tabs locally, then copy the refreshed Keychain credentials
#   to the Colossus host.

set -euo pipefail

fail() { echo "✗ $*" >&2; exit 1; }
bold() { printf "\033[1m%s\033[0m\n" "$*"; }
ok() { echo "✓ $*"; }

usage() {
    cat <<'USAGE'
Usage:
  ./scripts/mac-reauth-and-sync.sh <ssh-host> [-- <agent-me-codex-reauth args>]

Examples:
  ./scripts/mac-reauth-and-sync.sh 1xA100-40
  ./scripts/mac-reauth-and-sync.sh 1xA100-40 -- --limit 2
  AGENT_ME_REAUTH_SERVERS=maas-nvbugs ./scripts/mac-reauth-and-sync.sh 1xA100-40

Run this on the Mac that has browser access to NVIDIA SSO, not on Colossus.
USAGE
}

if [[ $# -lt 1 || "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

[[ "$(uname -s)" == "Darwin" ]] || fail "run this on macOS so browser tabs open on the Mac"
command -v security >/dev/null || fail "security CLI not found (expected on macOS)"

HOST="$1"
shift
if [[ "${1:-}" == "--" ]]; then
    shift
fi

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

cd "$REPO_ROOT"

bold "Step 1 — refresh MaaS MCP auth on this Mac"
echo "Host to sync after auth: $HOST"
echo
echo "Complete the browser tabs that open. When the helper says auth calls are dispatched,"
echo "press Ctrl-C in this terminal after the tabs finish, then this script will sync."
echo

set +e
uv run agent-me-codex-reauth "$@"
status=$?
set -e

if [[ "$status" -ne 0 && "$status" -ne 130 ]]; then
    fail "reauth helper exited with status $status"
fi
ok "reauth helper finished or was interrupted after auth"

bold "Step 2 — sync refreshed Mac Keychain credentials to $HOST"
"$SCRIPT_DIR/sync-mcp-creds-to-host.sh" "$HOST"

bold "Step 3 — verify on host"
ssh "$HOST" 'cd ~/agent-me 2>/dev/null || cd /localhome/local-thaphan/agent-me; codex mcp list; uv run python -c "from agent_me.mcp_tokens import codex_mcp_token_env; env=codex_mcp_token_env(); print(f\"usable MaaS bearer tokens: {len(env)}\")"'

ok "Mac reauth + host sync complete"
